"use client"

import { create } from "zustand"
import { persist } from "zustand/middleware"

// Sample user data based on the PDF
export const sampleUsers = [
  // Computer Science & Engineering Students
  {
    id: "241620101056",
    name: "PRIYANSHU SINGH MAHAR",
    email: "priyanshu@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Computer Science & Engineering",
    semester: 2,
    attendance: 92.5,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "RAMESH SINGH",
    motherName: "GEETA DEVI",
    dateOfBirth: "11/02/2007",
    phone: "9528731865",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620101010",
    name: "ANKITA CHAURAKOTI",
    email: "ankita@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Computer Science & Engineering",
    semester: 2,
    attendance: 92.09,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "SHANKAR DATT CHAURAKOTI",
    motherName: "KAVITA CHAURAKOTI",
    dateOfBirth: "28/06/2007",
    phone: "6395235069",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620101043",
    name: "MONIKA",
    email: "monika@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Computer Science & Engineering",
    semester: 2,
    attendance: 89.6,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "MOHAN SINGH",
    motherName: "PRIYANKA DEVI",
    dateOfBirth: "01/02/2007",
    phone: "7906419747",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620101046",
    name: "NEHA KALONI",
    email: "neha@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Computer Science & Engineering",
    semester: 2,
    attendance: 88.1,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "LALIT MOHAN KALONI",
    motherName: "SUNITA KALONI",
    dateOfBirth: "09/09/2007",
    phone: "9627993153",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620101062",
    name: "SACHIN PANDEY",
    email: "sachin@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Computer Science & Engineering",
    semester: 2,
    attendance: 86.82,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "DINESH CHANDRA PANDEY",
    motherName: "REKHA DEVI",
    dateOfBirth: "15/04/2007",
    phone: "7818972375",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620101058",
    name: "RENU BASERA",
    email: "renu@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Computer Science & Engineering",
    semester: 2,
    attendance: 85.94,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "PRADEEP SINGH BASERA",
    motherName: "MANJU BASERA",
    dateOfBirth: "18/11/2006",
    phone: "9758424484",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620101020",
    name: "DEV SAXENA",
    email: "dev@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Computer Science & Engineering",
    semester: 2,
    attendance: 84.85,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "RAMESH SAXENA",
    motherName: "MAHESHWARI SAXENA",
    dateOfBirth: "08/04/2005",
    phone: "7037521121",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620101007",
    name: "ADITYA RAJ NEGI",
    email: "aditya@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Computer Science & Engineering",
    semester: 2,
    attendance: 84.73,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "BHARAT SINGH NEGI",
    motherName: "RAJANI NEGI",
    dateOfBirth: "24/12/2005",
    phone: "8586020810",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620101034",
    name: "KRIPA RAWAT",
    email: "kripa@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Computer Science & Engineering",
    semester: 2,
    attendance: 84.17,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "VISHWANATH SINGH RAWAT",
    motherName: "UMA RAWAT",
    dateOfBirth: "16/07/2006",
    phone: "8077125860",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620101033",
    name: "KARTIK CHILKOTI",
    email: "kartik@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Computer Science & Engineering",
    semester: 2,
    attendance: 83.87,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "MADAN MOHAN CHILKOTI",
    motherName: "POOJA CHILKOTI",
    dateOfBirth: "15/12/2006",
    phone: "9568885012",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },

  // Artificial Intelligence and Machine Learning Students
  {
    id: "241620122010",
    name: "DISHA PANDEY",
    email: "disha@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Artificial Intelligence and Machine Learning",
    semester: 2,
    attendance: 93.28,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "TARA DUTT PANDEY",
    motherName: "GEETA PANDEY",
    dateOfBirth: "21/08/2006",
    phone: "9548640373",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620122023",
    name: "ROHIT DIGARI",
    email: "rohit@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Artificial Intelligence and Machine Learning",
    semester: 2,
    attendance: 93.13,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "PRAKASH SINGH DIGARI",
    motherName: "SEEMA DIGARI",
    dateOfBirth: "09/03/2007",
    phone: "9027119782",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620122008",
    name: "BHAWANA JOSHI",
    email: "bhawana@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Artificial Intelligence and Machine Learning",
    semester: 2,
    attendance: 91.73,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "BHUVAN CHANDRA JOSHI",
    motherName: "SAVITA DEVI",
    dateOfBirth: "03/09/2008",
    phone: "8449608671",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620122012",
    name: "HIMANSHU MAURYA",
    email: "himanshu@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Artificial Intelligence and Machine Learning",
    semester: 2,
    attendance: 90.08,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "RAJNATH PRASAD",
    motherName: "MEENA MAURYA",
    dateOfBirth: "10/07/2005",
    phone: "7055597687",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620122019",
    name: "PRATYAKSH SINGH BISHT",
    email: "pratyaksh@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Artificial Intelligence and Machine Learning",
    semester: 2,
    attendance: 72.18,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "CHANDAN SINGH BISHT",
    motherName: "RAMA BISHT",
    dateOfBirth: "17/02/2006",
    phone: "7017404469",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620122017",
    name: "PRADEEP SINGH BISHT",
    email: "pradeep@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Artificial Intelligence and Machine Learning",
    semester: 2,
    attendance: 68.46,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "RAM SINGH BISHT",
    motherName: "HEMA BISHT",
    dateOfBirth: "16/01/2006",
    phone: "7417925963",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620122016",
    name: "PIYUSH BHATT",
    email: "piyush@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Artificial Intelligence and Machine Learning",
    semester: 2,
    attendance: 65.63,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "OM PRAKASH BHATT",
    motherName: "SUNITA BHATT",
    dateOfBirth: "07/05/2006",
    phone: "9410100415",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },

  // Robotics & Automation Students
  {
    id: "241620129004",
    name: "SANGAM RAWAT",
    email: "sangam@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Robotics & Automation",
    semester: 2,
    attendance: 80.0,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "JAIPAL SINGH",
    motherName: "VINEETA DEVI RAWAT",
    dateOfBirth: "30/06/2005",
    phone: "7464932123",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "241620129003",
    name: "ROHIT BISHT",
    email: "rohitb@uktu.ac.in",
    password: "12345",
    role: "student",
    department: "Robotics & Automation",
    semester: 2,
    attendance: 79.39,
    leavesTaken: 0,
    maxLeaves: 3,
    fatherName: "HARISH SINGH",
    motherName: "KAMLA DEVI",
    dateOfBirth: "21/08/2005",
    phone: "9560133981",
    address: "Tanakpur",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },

  // Teacher and Admin accounts
  {
    id: "T67890",
    name: "Prof. Anderson",
    email: "anderson@uktu.ac.in",
    password: "12345",
    role: "teacher",
    department: "Computer Science & Engineering",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
  {
    id: "A11111",
    name: "Admin User",
    email: "admin@uktu.ac.in",
    password: "12345",
    role: "admin",
    institute: "DR. A.P.J ABDUL KALAM INSTITUTE OF TECHNOLOGY, TANAKPUR",
  },
]

// Define the auth store type
type AuthState = {
  user: (typeof sampleUsers)[0] | null
  isAuthenticated: boolean
  login: (userId: string, password: string) => { success: boolean; message: string }
  logout: () => void
}

// Create the auth store with persistence
export const useAuthStore = create<AuthState>()(
  persist(
    (set) => ({
      user: null,
      isAuthenticated: false,
      login: (userId, password) => {
        const user = sampleUsers.find((u) => u.id === userId && u.password === password)

        if (user) {
          set({ user, isAuthenticated: true })
          return { success: true, message: "Login successful" }
        }

        return { success: false, message: "Invalid ID or password" }
      },
      logout: () => {
        set({ user: null, isAuthenticated: false })
      },
    }),
    {
      name: "auth-storage",
    },
  ),
)

